language: node_js
node_js:
- 'node'
- 'lts/*'
addons:
  chrome: stable
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
- wget -N http://chromedriver.storage.googleapis.com/$(wget -qO- http://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
script:
- npm run build
- npm run coveralls